const SUPABASE_URL='https://hjmbajbhhglqzqetptys.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_ePthilRsYOzeHYbqrpZ7cg_iDoke9jk';
const BUCKET='publication-visuals';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const STATUS={idea:'Idée',draft:'Brouillon',review:'À valider',approved:'Validée',published:'Publiée'};
let user=null,clients=[],posts=[],month=new Date(new Date().getFullYear(),new Date().getMonth(),1),view='calendar',visualFile=null,removeVisual=false,dragId=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const byClient=id=>clients.find(c=>c.id===id);
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2400)};
function busy(v){document.body.classList.toggle('is-loading',v)}
function authMsg(m='',err=false){$('authMessage').textContent=m;$('authMessage').classList.toggle('hidden',!m);$('authMessage').classList.toggle('error',err)}
function showAuth(){ $('authScreen').classList.remove('hidden');$('appShell').classList.add('hidden') }
function showApp(){ $('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('userEmail').textContent=user?.email||'Compte connecté' }
async function load(){const [a,b]=await Promise.all([db.from('clients').select('*').order('name'),db.from('publications').select('*').order('publication_date').order('publication_time')]);if(a.error)throw a.error;if(b.error)throw b.error;clients=a.data||[];posts=(b.data||[]).map(r=>({id:r.id,client:r.client_id,title:r.title,category:r.category||'',platforms:r.networks||[],date:r.publication_date,time:(r.publication_time||'').slice(0,5),type:r.format,status:r.status,caption:r.caption||'',notes:r.notes||'',visual:r.visual_path||''}));render()}
async function afterLogin(){const {data,error}=await db.auth.getUser();if(error||!data.user){user=null;showAuth();return}user=data.user;showApp();busy(true);try{await load()}catch(e){console.error(e);toast('Impossible de charger les données')}finally{busy(false)}}
async function signIn(e){e.preventDefault();authMsg('Connexion…');const {error}=await db.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});error?authMsg('Connexion impossible. Vérifie tes identifiants et la confirmation de ton email.',true):authMsg('')}
async function signUp(){const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||password.length<6)return authMsg('Renseigne un email et un mot de passe de 6 caractères minimum.',true);const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(error)return authMsg(error.message,true);authMsg(data.session?'Compte créé. Connexion en cours…':'Compte créé. Confirme ton email puis reconnecte-toi.')}
function populateClients(){const prev=$('filterClient').value||'all',postPrev=$('postClient').value||'';$('clientList').innerHTML=clients.length?clients.map(c=>`<button class="client-item client-filter-btn" data-client="${c.id}"><span class="client-dot" style="background:${c.color}"></span>${esc(c.name)}</button>`).join(''):'<div class="sidebar-empty">Aucun client</div>';const opts=clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('filterClient').innerHTML='<option value="all">Tous les clients</option>'+opts;$('postClient').innerHTML=clients.length?'<option value="" disabled>Choisir un client</option>'+opts:'<option value="" disabled selected>Ajoutez d’abord un client</option>';if(prev==='all'||byClient(prev))$('filterClient').value=prev;if(byClient(postPrev))$('postClient').value=postPrev;document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>{$('filterClient').value=b.dataset.client;renderAll();$('sidebar').classList.remove('open')})}
function categories(){const p=$('filterCategory').value||'all',vals=[...new Set(posts.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));$('filterCategory').innerHTML='<option value="all">Toutes les catégories</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('');$('filterCategory').value=vals.includes(p)?p:'all'}
function clientManager(){$('clientManagerList').innerHTML=clients.length?clients.map(c=>`<div class="client-manager-row"><div class="client-manager-info"><span class="client-dot large" style="background:${c.color}"></span><div><strong>${esc(c.name)}</strong><span>${posts.filter(p=>p.client===c.id).length} publication(s)</span></div></div><div class="client-row-actions"><button class="secondary-btn small-btn" data-edit-client="${c.id}">Modifier</button><button class="danger-link" data-del-client="${c.id}">Supprimer</button></div></div>`).join(''):'<div class="empty-state"><strong>Aucun client enregistré</strong>Ajoute ton premier client.</div>';document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>{const c=byClient(b.dataset.editClient);$('clientId').value=c.id;$('clientName').value=c.name;$('clientColor').value=c.color;$('saveClientBtn').textContent='Enregistrer';$('cancelClientEdit').classList.remove('hidden')});document.querySelectorAll('[data-del-client]').forEach(b=>b.onclick=()=>deleteClient(b.dataset.delClient))}
async function saveClient(e){e.preventDefault();const id=$('clientId').value,payload={name:$('clientName').value.trim(),color:$('clientColor').value,user_id:user.id};if(!payload.name)return;busy(true);try{const q=id?db.from('clients').update(payload).eq('id',id):db.from('clients').insert(payload);const {error}=await q;if(error)throw error;resetClient();await load();toast(id?'Client modifié':'Client ajouté')}catch(e){console.error(e);toast('Erreur lors de l’enregistrement')}finally{busy(false)}}
function resetClient(){$('clientForm').reset();$('clientId').value='';$('clientColor').value='#6d4aff';$('saveClientBtn').textContent='Ajouter';$('cancelClientEdit').classList.add('hidden')}
async function deleteClient(id){const c=byClient(id);if(!c||!confirm(`Supprimer “${c.name}” et ses publications éventuelles ?`))return;busy(true);try{const linked=posts.filter(p=>p.client===id),{error}=await db.from('clients').delete().eq('id',id);if(error)throw error;const paths=linked.map(p=>p.visual).filter(Boolean);if(paths.length)await db.storage.from(BUCKET).remove(paths);await load();toast('Client supprimé')}catch(e){console.error(e);toast('Suppression impossible')}finally{busy(false)}}
function filtered(){const f={c:$('filterClient').value,p:$('filterPlatform').value,s:$('filterStatus').value,g:$('filterCategory').value,q:$('searchInput').value.trim().toLowerCase()};return posts.filter(x=>{const text=`${x.title} ${x.caption} ${x.notes} ${x.category} ${(x.platforms||[]).join(' ')} ${byClient(x.client)?.name||''}`.toLowerCase();return(f.c==='all'||x.client===f.c)&&(f.p==='all'||x.platforms.includes(f.p))&&(f.s==='all'||x.status===f.s)&&(f.g==='all'||x.category===f.g)&&(!f.q||text.includes(f.q))})}
function postCard(p){const c=byClient(p.client);return `<button class="calendar-post ${p.status}" draggable="true" data-post="${p.id}"><div class="post-time">${esc(p.time||'—')} · ${esc(p.platforms.map(x=>x.slice(0,2).toUpperCase()).join(' · '))}${p.visual?' · ▧':''}</div><div class="post-name">${esc(p.title)}</div><div class="post-meta"><span style="color:${c?.color||'#999'}">●</span> ${esc(c?.name||'')}</div></button>`}
function calendar(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),off=(first.getDay()+6)%7,start=new Date(y,m,1-off),fp=filtered();$('monthLabel').textContent=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(month);let h='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d),ps=fp.filter(p=>p.date===k).sort((a,b)=>a.time.localeCompare(b.time));h+=`<div class="day-cell ${d.getMonth()!==m?'outside':''} ${k===dateKey(new Date())?'today':''}" data-date="${k}"><div class="day-head"><span class="day-number">${d.getDate()}</span><button class="day-add" data-add="${k}">＋</button></div><div class="day-posts">${ps.slice(0,3).map(postCard).join('')}${ps.length>3?`<div class="more-posts">+ ${ps.length-3} autre(s)</div>`:''}</div></div>`}$('calendarGrid').innerHTML=h;bindPostActions()}
function list(){const fp=filtered();$('listCount').textContent=`${fp.length} publication${fp.length>1?'s':''}`;$('postsList').innerHTML=fp.length?fp.map(p=>{const c=byClient(p.client);return `<div class="post-row clickable" data-post="${p.id}"><div><strong>${new Date(p.date+'T12:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}</strong><div class="row-sub">${esc(p.time)}</div></div><div><div class="row-title">${p.visual?'▧ ':''}${esc(p.title)}</div><div class="row-sub">${esc(p.category)}</div></div><div class="col-client">${esc(c?.name||'')}</div><div class="col-platform">${esc(p.platforms.join(' · '))}</div><div class="col-format">${esc(p.type)}</div><div><span class="status-pill ${p.status}">${STATUS[p.status]}</span></div></div>`}).join(''):'<div class="empty-state"><strong>Aucune publication</strong>Ajoute ta première publication.</div>';bindPostActions()}
function stats(){const mm=posts.filter(p=>{const d=new Date(p.date+'T12:00');return d.getMonth()===month.getMonth()&&d.getFullYear()===month.getFullYear()});$('statTotal').textContent=mm.length;$('statReview').textContent=mm.filter(p=>p.status==='review').length;$('statApproved').textContent=mm.filter(p=>p.status==='approved').length;$('statPublished').textContent=mm.filter(p=>p.status==='published').length}
function renderAll(){stats();view==='calendar'?calendar():list()}
function render(){populateClients();categories();clientManager();renderAll()}
function bindPostActions(){document.querySelectorAll('[data-post]').forEach(el=>{el.onclick=()=>openEdit(el.dataset.post);el.ondragstart=e=>{dragId=el.dataset.post;e.dataTransfer.effectAllowed='move';el.classList.add('dragging')};el.ondragend=()=>{dragId=null;el.classList.remove('dragging')}});document.querySelectorAll('.day-cell').forEach(c=>{c.ondragover=e=>{e.preventDefault();c.classList.add('drag-over')};c.ondragleave=()=>c.classList.remove('drag-over');c.ondrop=async e=>{e.preventDefault();c.classList.remove('drag-over');if(!dragId)return;const {error}=await db.from('publications').update({publication_date:c.dataset.date}).eq('id',dragId);if(error)toast('Déplacement impossible');else{await load();toast('Publication déplacée')}}});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();openNew(b.dataset.add)})}
function openNew(date=dateKey(new Date())){if(!clients.length){$('clientModalBackdrop').classList.remove('hidden');return toast('Ajoute d’abord un client')}resetPost();$('postDate').value=date;$('postModalBackdrop').classList.remove('hidden')}
function openEdit(id){const p=posts.find(x=>x.id===id);if(!p)return;resetPost();$('postId').value=p.id;$('modalTitle').textContent='Modifier la publication';$('postTitle').value=p.title;$('postClient').value=p.client;$('postCategory').value=p.category;$('postDate').value=p.date;$('postTime').value=p.time;$('postType').value=p.type;$('postStatus').value=p.status;$('postCaption').value=p.caption;$('postNotes').value=p.notes;document.querySelectorAll('[name=postPlatform]').forEach(x=>x.checked=p.platforms.includes(x.value));$('deletePostBtn').classList.remove('hidden');if(p.visual)previewExisting(p.visual);$('postModalBackdrop').classList.remove('hidden')}
function resetPost(){$('postForm').reset();$('postId').value='';$('modalTitle').textContent='Nouvelle publication';$('deletePostBtn').classList.add('hidden');visualFile=null;removeVisual=false;$('visualPreviewWrap').classList.add('hidden');$('visualPreview').removeAttribute('src')}
async function previewExisting(path){const {data}=await db.storage.from(BUCKET).createSignedUrl(path,3600);if(data?.signedUrl){$('visualPreview').src=data.signedUrl;$('visualPreviewWrap').classList.remove('hidden')}}
async function savePost(e){e.preventDefault();const id=$('postId').value,platforms=[...document.querySelectorAll('[name=postPlatform]:checked')].map(x=>x.value);if(!platforms.length)return toast('Choisis au moins un réseau');busy(true);try{let visual=posts.find(p=>p.id===id)?.visual||null;if(removeVisual&&visual){await db.storage.from(BUCKET).remove([visual]);visual=null}if(visualFile){if(visual)await db.storage.from(BUCKET).remove([visual]);const ext=(visualFile.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/${crypto.randomUUID()}.${ext}`,up=await db.storage.from(BUCKET).upload(path,visualFile,{contentType:visualFile.type,upsert:false});if(up.error)throw up.error;visual=path}const payload={user_id:user.id,client_id:$('postClient').value,title:$('postTitle').value.trim(),category:$('postCategory').value.trim()||null,networks:platforms,publication_date:$('postDate').value,publication_time:$('postTime').value||null,format:$('postType').value,status:$('postStatus').value,caption:$('postCaption').value.trim()||null,notes:$('postNotes').value.trim()||null,visual_path:visual};const q=id?db.from('publications').update(payload).eq('id',id):db.from('publications').insert(payload),{error}=await q;if(error)throw error;$('postModalBackdrop').classList.add('hidden');await load();toast(id?'Publication modifiée':'Publication créée')}catch(e){console.error(e);toast('Enregistrement impossible')}finally{busy(false)}}
async function deletePost(){const id=$('postId').value,p=posts.find(x=>x.id===id);if(!p||!confirm('Supprimer cette publication ?'))return;busy(true);try{const {error}=await db.from('publications').delete().eq('id',id);if(error)throw error;if(p.visual)await db.storage.from(BUCKET).remove([p.visual]);$('postModalBackdrop').classList.add('hidden');await load();toast('Publication supprimée')}catch(e){console.error(e);toast('Suppression impossible')}finally{busy(false)}}
$('authForm').addEventListener('submit',signIn);$('signUpBtn').onclick=signUp;$('logoutBtn').onclick=()=>db.auth.signOut();$('clientForm').addEventListener('submit',saveClient);$('cancelClientEdit').onclick=resetClient;$('openClientManager').onclick=()=>{$('clientModalBackdrop').classList.remove('hidden');resetClient()};$('closeClientModal').onclick=()=> $('clientModalBackdrop').classList.add('hidden');$('postForm').addEventListener('submit',savePost);$('newPostBtn').onclick=()=>openNew();$('closeModal').onclick=$('cancelPost').onclick=()=>$('postModalBackdrop').classList.add('hidden');$('deletePostBtn').onclick=deletePost;$('postVisual').onchange=e=>{visualFile=e.target.files?.[0]||null;removeVisual=false;if(visualFile){$('visualPreview').src=URL.createObjectURL(visualFile);$('visualPreviewWrap').classList.remove('hidden')}};$('removeVisualBtn').onclick=()=>{visualFile=null;removeVisual=true;$('postVisual').value='';$('visualPreviewWrap').classList.add('hidden')};['filterClient','filterPlatform','filterStatus','filterCategory'].forEach(id=>$(id).onchange=renderAll);$('searchInput').oninput=renderAll;$('resetFilters').onclick=()=>{$('filterClient').value=$('filterPlatform').value=$('filterStatus').value=$('filterCategory').value='all';$('searchInput').value='';renderAll()};$('prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderAll()};$('nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderAll()};$('todayBtn').onclick=()=>{const n=new Date();month=new Date(n.getFullYear(),n.getMonth(),1);renderAll()};$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('calendarView').classList.toggle('hidden',view!=='calendar');$('listView').classList.toggle('hidden',view!=='list');renderAll()});db.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;user?afterLogin():showAuth()});afterLogin();
