const SUPABASE_URL='https://hjmbajbhhglqzqetptys.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_ePthilRsYOzeHYbqrpZ7cg_iDoke9jk';
const clientDb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const ce=id=>document.getElementById(id);
const CSTATUS={review:'À valider',changes_requested:'Modification demandée',approved:'Validée',published:'Publiée'};
let portalUser=null,portalClients=[],portalPosts=[],portalFeedback=[],activeClientId=null,portalMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),activePostId=null;
const inviteToken=new URL(location.href).searchParams.get('invite');
const cesc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const cdateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function ctoast(m){const t=ce('clientToast');t.textContent=m;t.classList.remove('hidden');clearTimeout(ctoast.t);ctoast.t=setTimeout(()=>t.classList.add('hidden'),2600)}
function authMessage(m='',err=false){ce('clientAuthMessage').textContent=m;ce('clientAuthMessage').classList.toggle('hidden',!m);ce('clientAuthMessage').classList.toggle('error',err)}
function showClientAuth(){ce('clientAuth').classList.remove('hidden');ce('clientPortal').classList.add('hidden')}
function showClientPortal(){ce('clientAuth').classList.add('hidden');ce('clientPortal').classList.remove('hidden');ce('clientAccountEmail').textContent=portalUser?.email||''}
function cleanInvite(){const u=new URL(location.href);u.searchParams.delete('invite');history.replaceState({},'',u.pathname+u.search+u.hash)}
async function signInClient(e){e.preventDefault();authMessage('Connexion…');const {error}=await clientDb.auth.signInWithPassword({email:ce('clientEmail').value.trim(),password:ce('clientPassword').value});error?authMessage('Connexion impossible. Vérifiez vos identifiants et la confirmation de votre email.',true):authMessage('')}
async function signUpClient(){const email=ce('clientEmail').value.trim(),password=ce('clientPassword').value;if(!email||password.length<6)return authMessage('Renseignez un email et un mot de passe de 6 caractères minimum.',true);const {data,error}=await clientDb.auth.signUp({email,password,options:{emailRedirectTo:location.href}});if(error)return authMessage(error.message,true);authMessage(data.session?'Compte créé. Connexion en cours…':'Compte créé. Confirmez votre email puis revenez sur ce lien.')}
async function acceptInvite(){if(!inviteToken)return true;const {data,error}=await clientDb.functions.invoke('client-invite-accept',{body:{token:inviteToken}});if(error){let msg='Impossible d’accepter cette invitation.';try{const p=await error.context?.json?.();if(p?.error==='email_mismatch')msg=`Cette invitation est réservée à ${p.expected_email}.`;if(p?.error==='invite_expired')msg='Cette invitation a expiré. Demandez un nouveau lien à Brothers Studios.';if(p?.error==='invite_already_used')msg='Cette invitation a déjà été utilisée.';}catch{}authMessage(msg,true);return false}if(data?.ok){cleanInvite();ctoast('Votre accès client est activé');return true}return false}
async function loadPortalData(){const {data,error}=await clientDb.functions.invoke('client-calendar-data',{body:{}});if(error)throw error;portalClients=data?.clients||[];portalPosts=(data?.publications||[]).map(p=>({...p,time:(p.publication_time||'').slice(0,5)}));portalFeedback=data?.feedback||[];if(!activeClientId||!portalClients.some(c=>c.id===activeClientId))activeClientId=portalClients[0]?.id||null;renderPortal()}
async function afterClientLogin(){const {data,error}=await clientDb.auth.getUser();if(error||!data.user){portalUser=null;showClientAuth();return}portalUser=data.user;showClientPortal();if(inviteToken){const ok=await acceptInvite();if(!ok)return}try{await loadPortalData()}catch(e){console.error(e);ctoast('Impossible de charger votre calendrier')}}
function renderPortal(){if(!portalClients.length){ce('noClientAccess').classList.remove('hidden');ce('portalContent').classList.add('hidden');ce('clientName').textContent='Votre espace';return}ce('noClientAccess').classList.add('hidden');ce('portalContent').classList.remove('hidden');const current=portalClients.find(c=>c.id===activeClientId)||portalClients[0];activeClientId=current.id;ce('clientName').textContent=current.name;const sel=ce('clientSelector');sel.innerHTML=portalClients.map(c=>`<option value="${c.id}">${cesc(c.name)}</option>`).join('');sel.value=activeClientId;sel.classList.toggle('hidden',portalClients.length<2);renderClientStats();renderClientCalendar()}
function currentPosts(){return portalPosts.filter(p=>p.client_id===activeClientId)}
function renderClientStats(){const p=currentPosts();ce('clientStatReview').textContent=p.filter(x=>x.status==='review').length;ce('clientStatChanges').textContent=p.filter(x=>x.status==='changes_requested').length;ce('clientStatApproved').textContent=p.filter(x=>x.status==='approved').length;ce('clientStatPublished').textContent=p.filter(x=>x.status==='published').length}
function clientPostCard(p){return `<button class="calendar-post ${p.status}" data-client-post="${p.id}"><div class="post-time">${cesc(p.time||'—')} · ${cesc((p.networks||[]).map(x=>x.slice(0,2).toUpperCase()).join(' · '))}</div><div class="post-title">${cesc(p.title)}</div><div class="post-status">${cesc(CSTATUS[p.status]||p.status)}</div></button>`}
function renderClientCalendar(){const y=portalMonth.getFullYear(),m=portalMonth.getMonth(),first=new Date(y,m,1),off=(first.getDay()+6)%7,start=new Date(y,m,1-off),posts=currentPosts();ce('clientMonthLabel').textContent=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(portalMonth);let h='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=cdateKey(d),ps=posts.filter(p=>p.publication_date===k).sort((a,b)=>(a.time||'').localeCompare(b.time||''));h+=`<div class="day-cell ${d.getMonth()!==m?'outside':''} ${k===cdateKey(new Date())?'today':''}"><span class="day-number">${d.getDate()}</span><div class="day-posts">${ps.map(clientPostCard).join('')}</div></div>`}ce('clientCalendar').innerHTML=h;document.querySelectorAll('[data-client-post]').forEach(b=>b.onclick=()=>openClientPost(b.dataset.clientPost))}
async function openClientPost(id){const p=portalPosts.find(x=>x.id===id);if(!p)return;activePostId=id;ce('clientPostTitle').textContent=p.title;ce('postNetworks').textContent=(p.networks||[]).join(' · ');ce('clientPostDate').textContent=new Date(p.publication_date+'T12:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});ce('clientPostFormat').textContent=p.format||'—';ce('clientPostCategory').textContent=p.category||'—';ce('clientPostCaption').textContent=p.caption||'Aucun texte renseigné.';const pill=ce('clientPostStatus');pill.textContent=CSTATUS[p.status]||p.status;pill.className=`status-pill ${p.status}`;renderFeedbackHistory(id);ce('clientFeedbackMessage').value='';const canReview=['review','changes_requested','approved'].includes(p.status)&&p.status!=='published';ce('clientReviewActions').classList.toggle('hidden',!canReview);ce('approvePost').classList.toggle('hidden',!['review','changes_requested'].includes(p.status));ce('requestChanges').classList.toggle('hidden',!['review','changes_requested','approved'].includes(p.status));ce('clientVisualWrap').classList.add('hidden');ce('clientVisual').removeAttribute('src');ce('clientPostBackdrop').classList.remove('hidden');if(p.has_visual){try{const {data,error}=await clientDb.functions.invoke('client-visual-url',{body:{publication_id:id}});if(!error&&data?.signed_url){ce('clientVisual').src=data.signed_url;ce('clientVisualWrap').classList.remove('hidden')}}catch(e){console.error(e)}}}
function renderFeedbackHistory(id){const items=portalFeedback.filter(f=>f.publication_id===id);ce('clientFeedbackHistory').innerHTML=items.length?items.map(f=>`<div class="feedback-item ${f.action}"><strong>${f.action==='approved'?'Publication validée':f.action==='changes_requested'?'Modification demandée':'Commentaire'}</strong>${f.message?`<p>${cesc(f.message)}</p>`:''}<time>${new Date(f.created_at).toLocaleString('fr-FR')}</time></div>`).join(''):'<div class="history-empty">Aucun échange pour le moment.</div>'}
async function submitReview(action){if(!activePostId)return;const message=ce('clientFeedbackMessage').value.trim();if(action==='changes_requested'&&!message)return ctoast('Indiquez la modification souhaitée.');if(action==='comment'&&!message)return ctoast('Écrivez un commentaire.');const button=action==='approved'?ce('approvePost'):action==='changes_requested'?ce('requestChanges'):ce('addComment');button.disabled=true;try{const {data,error}=await clientDb.functions.invoke('client-review',{body:{publication_id:activePostId,action,message}});if(error||!data?.ok)throw error||new Error('review_failed');const reopen=activePostId;await loadPortalData();await openClientPost(reopen);ctoast(action==='approved'?'Publication validée':action==='changes_requested'?'Modification demandée':'Commentaire ajouté')}catch(e){console.error(e);ctoast('Action impossible. Réessayez.')}finally{button.disabled=false}}
ce('clientAuthForm').addEventListener('submit',signInClient);ce('clientSignUp').onclick=signUpClient;ce('clientLogout').onclick=()=>clientDb.auth.signOut();ce('clientSelector').onchange=e=>{activeClientId=e.target.value;renderPortal()};ce('clientPrevMonth').onclick=()=>{portalMonth=new Date(portalMonth.getFullYear(),portalMonth.getMonth()-1,1);renderClientCalendar()};ce('clientNextMonth').onclick=()=>{portalMonth=new Date(portalMonth.getFullYear(),portalMonth.getMonth()+1,1);renderClientCalendar()};ce('clientToday').onclick=()=>{const n=new Date();portalMonth=new Date(n.getFullYear(),n.getMonth(),1);renderClientCalendar()};ce('closeClientPost').onclick=()=>ce('clientPostBackdrop').classList.add('hidden');ce('clientPostBackdrop').onclick=e=>{if(e.target===ce('clientPostBackdrop'))ce('clientPostBackdrop').classList.add('hidden')};ce('approvePost').onclick=()=>submitReview('approved');ce('requestChanges').onclick=()=>submitReview('changes_requested');ce('addComment').onclick=()=>submitReview('comment');if(inviteToken)ce('inviteBadge').classList.remove('hidden');clientDb.auth.onAuthStateChange((_e,s)=>{portalUser=s?.user||null;portalUser?afterClientLogin():showClientAuth()});afterClientLogin();
